### ISSUE TITLE
final form page content work

### ISSUE THREAD

**Issue by leahbannon** [18F/beta.foia.gov#264]
- [x] add glossary links
- [ ] final review/edit

**Comment by RyanSibley** [comment]
https://docs.google.com/a/gsa.gov/document/d/17QkHrbrhaR3Tw7gzgjrgDjxIGkZXTkymD5AMFq7ZqOw/edit?usp=sharing

**Comment by adborden** [comment]
@RyanSibley you have the "Additional information" section as the third section in your doc, is that where you really want it to appear in the form? This is where you want the 10% fields to go?

**Comment by RyanSibley** [comment]
Yes, thank you -- this is where I want the 10 percent fields to go, if any.
Do you see any problem with this?

**Comment by adborden** [comment]
I think it's fine. The ordering of the fields is tricky because we don't know the names of the 10% fields. We should be keeping the order we get from the back stage, so the attachments field should appear above any 10% fields 🤞 

The request summary on the confirmation page is a little tricky, but I think we can make it work.
