### ISSUE TITLE
plan for using a feedback bar or a messaging indicating a page will no longer be updated

### ISSUE THREAD

**Issue by RyanSibley** [18F/beta.foia.gov#295]
As a foia.gov visitor, in order to understand that the content that I am looking for on foia.gov will be improved upon in the future or that it will no longer be updated, I need a message indicating as much and telling me what action I need to take to get updated information, if any.

Context:
- All content from the old FOIA.gov (the legacy site) will be ported over to the new site (also FOIA.gov and currently available as a [preview](http://foiafrontstg.prod.acquia-sites.com)).
- People will access new content, the requester portal, and the legacy content, on the new FOIA.gov. 
- All pages on the new site will receive a Jekyll treatment (will have the new header/footer).
- Some legacy content will no longer be updated so if people go to a page with content that is out of date, or may become outdated in the future, we need to indicate that and tell them where to find the updated information.
- Right now there is no plan to do a redirect for pages. 
- If we do redirect pages, they would be redirecting within the same site. 
- archive.foia.gov will have a copy of all the legacy content, but the public won't ever be directed there. 

Things to do:

1. Decide which pages gets a `this page is not being updated message` and which pages get a feedback message.  (https://docs.google.com/a/gsa.gov/spreadsheets/d/12LdK_BjmzGuvTVzcNxicui_Zzo8BOLkN-2dAf9XBWGo/edit?usp=sharing)
2. Write the two messages (ryan will do) https://docs.google.com/a/gsa.gov/document/d/1hzt4GKgx6RvIPSZ4dDIyXiu3iMghWzb50FtZTkbvyc8/edit?usp=sharing
3. design the banners

Related: 

https://github.com/18F/beta.foia.gov/issues/227
https://github.com/18F/beta.foia.gov/issues/226

 

cc @adborden @leahbannon

**Comment by RyanSibley** [comment]
From @adborden:

Here's how I'm thinking this will work. Folks who have https://www.foia.gov/report-makerequest.html bookmarked, they will see this on the new foia.gov. We can add a banner for different pages with something like "this content has moved to X" or "this page is in transition, but the content is still accurate", or whatever. We can do page-specific banners depending on the situation.

**Comment by adborden** [comment]
> Here's how I'm thinking this will work. Folks who have https://www.foia.gov/report-makerequest.html bookmarked, they will see this on the new foia.gov. We can add a banner for different pages with something like "this content has moved to X" or "this page is in transition, but the content is still accurate", or whatever. We can do page-specific banners depending on the situation.

Yes, they will see this page on the new foia.gov: http://foiafrontdev.prod.acquia-sites.com/report-makerequest.html

**Comment by leahbannon** [comment]
Can you let me know if this is right? I'm still not sure I understand the plan. (This is just as I understand it, I don't have a preference atm.)

There are 3 types of content:
- new content (e.g. the landing page and the request portal) -- this will have the standard beta banner asking people to contact us for feedback if necessary
- outdated legacy content (e.g. old blog posts) -- this will have the new header and be jekyllized, but it will also have banner warning that it might be outdated content and where to look for newer, similar content
- current legacy content (e.g. learn pages) -- this will have the new header and be jekyllized, and it will have the beta banner same as new content

Any time someone goes to an existing foia.gov URL, they will see that page with the treatment as above. There is no need to "redirect," because we're essentially just adding headers and banners, not removing anything.

This will all appear at the same URLs as before, https://foia.gov/... There will be no archive.foia.gov or beta.foia.gov.

**Comment by RyanSibley** [comment]
Yes, I think this is exactly right. Let me know what more I can do to firm this up to share more broadly.

**Comment by adborden** [comment]
Very well said @leahbannon, I like this concept model.

On the redirect comment, completely agree. I would emphasize that for the outdated legacy content, there are no "redirects" because there is no place to redirect _to_. Users still want to access that old content, we just need to communicate to them that it is outdated.

The "beta site" or "beta.foia.gov" is just a convenient name for the new site. Agreed that there will be no archive.foia.gov sites or beta.foia.gov websites.

**Comment by RyanSibley** [comment]
I've started identifying what pages get what treatment here: https://docs.google.com/a/gsa.gov/spreadsheets/d/12LdK_BjmzGuvTVzcNxicui_Zzo8BOLkN-2dAf9XBWGo/edit?usp=sharing

**Comment by adborden** [comment]
This is covered in #277
