### ISSUE TITLE
Create endpoint in Drupal for request form submissions

### ISSUE THREAD

**Issue by malikkotob** [18F/beta.foia.gov#92]
As a [user], in order to [accomplish some goal], I need [some feature].

With requests being submitted via API to the Drupal backend, an endpoint needs to be created to accept requests.

## Acceptance criteria

- [ ] An endpoint in Drupal exists to accept request form submissions

**Comment by adborden** [comment]
I think both from a strategy perspective and a technical perspective, it would be useful for this endpoint to implement our [agency API spec](https://github.com/18F/foia/blob/master/agency-api-spec.md). This allows us to get developers implementing the spec and provide feedback rather than waiting for agencies to book time to implement. It also means our submission API follows a well-defined spec.

**Comment by malikkotob** [comment]
Covered by #91
